# Example KiBot config file
kibot:
  version: 1

global:
  solder_mask_color: 'black'
  silk_screen_color: 'white'

outputs:
  - name: print_pdf
    comment: "PDF for the PCB"
    type: pcb_print
    options:
      force_edge_cuts: true
      keep_temporal_files: true
      scaling: 2.0
      pages:
        - layers: [ F.Paste, F.Adhes, Dwgs.User, F.Fab ]
          sheet: 'Fabrication layers'
        - layers:
            - layer: F.Cu
            - layer: F.Mask
              color: '#14332440'
            - layer: F.SilkS
            - layer: Dwgs.User
          sheet: 'Top layer'
        - layers:
            - layer: B.Cu
            - layer: B.Mask
              color: '#14332440'
            - layer: B.SilkS
            - layer: Dwgs.User
          sheet: 'Bottom layer'
          mirror: true

  - name: 3D
    comment: "STEP 3D model"
    type: step

  - name: 3D_top_view
    comment: "3D render from top"
    type: render_3d
    # see https://kibot.readthedocs.io/en/master/configuration/outputs/render_3d.html
    options:
      zoom: 4
      rotate_x: 3
      rotate_z: 3
      ray_tracing: true

  - name: 3D_top_view_HQ
    comment: "3D render from top (High Quality)"
    type: blender_export
    options:
      render_options:
        transparent_background: true
        samples: 20
      point_of_view:
        rotate_x: 30
        rotate_z: -20
      outputs:
        - type: blender
        - type: render
