#ifndef LIBSIO_H
#define LIBSIO_H
#include <psyz/types.h>

/**
 * @file libsio.h
 * @brief Serial Input/Output Library
 *
 * This library provides functions for serial communication via the SIO (Serial
 * I/O) port. It supports detailed communication control with a PC for debugging
 * and data transfer purposes.
 *
 * Key features:
 * - Driver initialization and removal
 * - Configurable communication parameters (speed, mode, control lines)
 * - Interrupt-driven operation with callback support
 * - Status monitoring and error detection
 */

/* Driver Status bits (returned by _sio_control(0, 0, 0)) */
#define SR_TXRDY 0x0001  /**< Bit 0: Able to write communications data */
#define SR_RXRDY 0x0002  /**< Bit 1: Able to read communications data */
#define SR_TXU 0x0004    /**< Bit 2: No communications data */
#define SR_PERROR 0x0008 /**< Bit 3: Parity error occurs */
#define SR_OE 0x0010     /**< Bit 4: Overrun error occurs */
#define SR_FE 0x0020     /**< Bit 5: Frame error occurs */
#define SR_DSR 0x0080    /**< Bit 7: DSR is on */
#define SR_CTS 0x0100    /**< Bit 8: CTS is on */
#define SR_IRQ 0x0200    /**< Bit 9: Interrupt is on */

/* Control Line Status bits (used with _sio_control(0/1, 1, param)) */
#define CR_DTR 0x0001 /**< Bit 0: DTR is on */
#define CR_RTS 0x0002 /**< Bit 1: RTS is on */

/* Communications Mode bits (used with _sio_control(0/1, 2, param)) */
#define MR_CHLEN_5 0x00 /**< Character length: 5 bits */
#define MR_CHLEN_6 0x04 /**< Character length: 6 bits */
#define MR_CHLEN_7 0x08 /**< Character length: 7 bits */
#define MR_CHLEN_8 0x0C /**< Character length: 8 bits */
#define MR_PEN 0x10     /**< Parity enabled */
#define MR_P_EVEN 0x20  /**< Parity: 1=odd, 0=even */
#define MR_SB_01 0x40   /**< Stop bit length: 1 */
#define MR_SB_10 0x80   /**< Stop bit length: 1.5 */
#define MR_SB_11 0xC0   /**< Stop bit length: 2 */

/* Control Register bits (used with _sio_control(1, 1, param)) */
#define CR_TXEN 0x0001   /**< Bit 0: Transmission permission */
#define CR_DTR 0x0002    /**< Bit 1: DTR is on */
#define CR_RXEN 0x0004   /**< Bit 2: Receive permission */
#define CR_ERRRST 0x0010 /**< Bit 4: Interrupt and error flag clear */
#define CR_RTS 0x0020    /**< Bit 5: RTS is on */
#define CR_INTRST 0x0040 /**< Bit 6: SIO1 Reset */
#define CR_TXIEN 0x0400  /**< Bit 10: Transmission Interrupt Permission */
#define CR_RXIEN 0x0800  /**< Bit 11: Receive Interrupt Permission */
#define CR_DSRIEN 0x1000 /**< Bit 12: DSR Interrupt Permission */

/**
 * @brief Initialize SIO driver
 *
 * Initializes the SIO driver at the specified communication speed.
 *
 * @param baud Communication speed in bps (bits per second)
 * @return 1
 */
long AddSIO(int baud);

/**
 * @brief Delete SIO driver from kernel
 *
 * Deletes the SIO driver from the kernel.
 *
 * @return 1
 */
long DelSIO(void);

/**
 * @brief Set SIO interrupt callback function
 *
 * Defines func as the callback to be triggered when an interrupt has been
 * generated by the interrupt factors (CR_DSRIEN, CR_RXIEN, CR_TXIEN) set by
 * _sio_control(1, 1, param). If func is 0, a callback is not generated.
 *
 * When an interrupt is generated, the interrupt flag must be cleared using
 * _sio_control(2, 1, 0) or _sio_control(1, 1, CR_ERRRST). The next SIO
 * interrupt won't be generated unless the interrupt flag is cleared.
 *
 * @param func Callback function (0 to disable)
 * @return Address of previously installed callback function
 */
int Sio1Callback(void (*func)());

/**
 * @brief Issue SIO command
 *
 * SIO driver control and information acquisition. Used for detailed
 * communication with a PC and for suppressing debugging data from the library.
 *
 * Command summary:
 * - cmd=0, arg=0: Returns driver status (SR_* bits)
 * - cmd=0, arg=1: Returns control line status (CR_DTR, CR_RTS bits)
 * - cmd=0, arg=2: Returns communications mode (MR_* bits)
 * - cmd=0, arg=3: Returns communications speed (bps units)
 * - cmd=0, arg=4: Reads 1 byte (param ignored)
 * - cmd=1, arg=0: System reservation
 * - cmd=1, arg=1: Sets param as control line status
 * - cmd=1, arg=2: Sets param as communications mode
 * - cmd=1, arg=3: Sets param as communications speed (bps)
 * - cmd=1, arg=4: Writes 1 byte (param = byte to write)
 * - cmd=2, arg=0: Resets driver
 * - cmd=2, arg=1: Clears driver status error-related bits
 *
 * @param cmd Command (0=get, 1=set, 2=reset)
 * @param arg Subcommand (see table above)
 * @param param Argument (depends on cmd/arg combination)
 * @return Depends on the command (see table above)
 */
long _sio_control(unsigned long cmd, unsigned long arg, unsigned long param);

#endif /* LIBSIO_H */
